"""remove value

Revision ID: 7eda3c372be1
Revises: cf29564e35e8
Create Date: 2026-07-24 19:53:15.690228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eda3c372be1'
down_revision: Union[str, Sequence[str], None] = 'cf29564e35e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_votes', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_votes', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
